%Diccionario
determinante --> [el].
determinante --> [la].
determinante --> [un].
determinante --> [una].
nombre --> [hombre].
nombre --> [mujer].
nombre --> [juan].
nombre --> [maria].
nombre --> [manzana].
nombre --> [manzanas].
nombre --> [gato].
nombre --> [raton].
nombre --> [ratones].
nombre --> [alumno].
nombre --> [universidad].
verbo --> [ama].
verbo --> [come].
verbo --> [estudia].
verbo --> [era].
verbo --> [es].
verbo --> [cazo].
adjetivo --> [roja].
adjetivo --> [negro].
adjetivo --> [grande].
adjetivo --> [gris].
adjetivo --> [pequeno].
preposicion --> [a].
preposicion --> [en].
adverbio --> [que].