%Diccionario
determinante --> [the].
determinante --> [a].
determinante --> [an].
nombre --> [man].
nombre --> [woman].
nombre --> [john].
nombre --> [mary].
nombre --> [apple].
nombre --> [apples].
nombre --> [cat].
nombre --> [mouse].
nombre --> [mice].
nombre --> [student].
nombre --> [university].
verbo --> [loves].
verbo --> [eats].
verbo --> [studies].
verbo --> [was].
verbo --> [is].
verbo --> [hunted].
adjetivo --> [red].
adjetivo --> [black].
adjetivo --> [big].
adjetivo --> [grey].
adjetivo --> [small].
preposicion --> [a].%%%%
preposicion --> [at].
adverbio --> [that].